fact1:
  - head-branch: ['fact1']

fact2:
  - head-branch: ['fact2']

# creating proper pattern is not an easy task. How do we speed up it?
#   1. Use a brand new repo where you can change without any team member approve
#   2. Turn on action debug mode to see actions output. See below
#
# use ACTIONS_STEP_DEBUG secret to turn on debugging
# see https://github.com/actions/toolkit/blob/master/docs/action-debugging.md
except-sub-project:
  - changed-files:
    # all files except, top-level files, and files listed in folders that start with `!`
    - all-globs-to-all-files:
        #- '**'
        - '!sub-project/src/**'
        - '!test*/**'

only-sub-project:
  - all:
    - changed-files:
      - any-glob-to-any-file:
          - 'sub-project/src/**'
          - 'test*/**'
          # temporary 
          - '.github/labeler.yml'