name: Test GHA workflow

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      RES: ${{ steps.set_output.outputs.RES }}
    steps:
      - uses: actions/labeler@v5
      - uses: Brightspace/third-party-actions@actions/checkout
        # For correct work of `Get PULL_REQUEST_NUMBER (push)`-step
        with:
          fetch-depth: 0

      - name: Get PULL_REQUEST_NUMBER (push)
        if: ${{ github.event_name == 'push' }}
        # get PR number from the latest commit
        run: |
          pr_number="$(git log -1 | grep -oP 'Merge pull request #\K\d+' || echo "")"
          echo "PULL_REQUEST_NUMBER=$pr_number"
          echo "PULL_REQUEST_NUMBER=$pr_number" >> $GITHUB_ENV

      - name: Get PULL_REQUEST_NUMBER (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "PULL_REQUEST_NUMBER=$PR_NUMBER"
          echo "PULL_REQUEST_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
      
      - name: Print PULL_REQUEST_NUMBER
        run: |
          echo "PR NUMBER: $PULL_REQUEST_NUMBER"

      - name: Set DEFAULT environment variables
        run: |
          condition_result=0;
          echo "RES=$condition_result"
          echo "RES=$condition_result" >> $GITHUB_ENV
          echo "RES=$condition_result" >> $GITHUB_OUTPUT

      - name: Label PR
        run: |
          if [ -z $PULL_REQUEST_NUMBER ]
          then
            echo There are no PRs available!
            exit 0;
          fi

          echo Warning! Ensure that .github/sub-project.regex contains LFs not CRLFs

          sub_project="$(gh pr diff $PULL_REQUEST_NUMBER --name-only | grep --quiet -E -i -f .github/sub-project.regex && echo $? || echo $?)"
          if [ $sub_project == 0 ]
          then
            echo Found changes in files that match patterns in .github/sub-project.regexp
            gh pr edit $PULL_REQUEST_NUMBER --add-label sub-project
          fi

          non_sub_project="$(gh pr diff $PULL_REQUEST_NUMBER --name-only | grep --quiet -E -i -v -f .github/sub-project.regex && echo $? || echo $?)"
          if [ $non_sub_project == 0 ]
          then
            echo Found changes in files that DO NOT MATCH patterns in .github/sub-project.regexp
            gh pr diff $PULL_REQUEST_NUMBER --name-only | grep -E -i -v -f .github/sub-project.regex | head
            gh pr edit $PULL_REQUEST_NUMBER --add-label except-sub-project
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set environment variables
        id: set_output
        run: |
          if [ -z $PULL_REQUEST_NUMBER ]
          then
            echo There are no PRs available! Using the default values of environment variables
            exit 0;
          fi
          fact1_label="$(gh api repos/$REPO/pulls/$PULL_REQUEST_NUMBER --jq 'if any(.labels.[]; .name=="sub-project") then 1 else 0 end')"
          fact2_label="$(gh api repos/$REPO/pulls/$PULL_REQUEST_NUMBER --jq 'if any(.labels.[]; .name=="except-sub-project") then 1 else 0 end')"
          condition_result=0
          if [ $fact1_label == 1 ] && [ $fact2_label == 0 ]
          then
            condition_result=1
          fi
          echo "RES=$condition_result"
          echo "RES=$condition_result" >> $GITHUB_ENV
          echo "RES=$condition_result" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}

  actual_job:
    if: ${{ needs.triage.outputs.RES != '1' }}
    needs: [ triage ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RES: ${{ needs.triage.outputs.RES }}
    steps: 
      - name: Greeting
        run: |
          echo Hello from Actual Job
          echo "RES=$RES"
  
  job_after:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [actual_job]
    # the job can get cancelled between steps
    # another comments
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Greeting 
        run: |
          echo "Hello from Actual Job. $ref"
        env:
          ref: ${{ github.ref }}
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: delay 01
        run: |
          node ./delay.js
      - name: delay 01
        run: |
          node ./delay.js
      - name: delay 02
        run: |
          node ./delay.js
      - name: delay 03
        run: |
          node ./delay.js

